version: '3.8'

services:
  web:
    build: .
    ports:
      - "5173:5173"  # Exposing the port for the React app
    volumes:
      - .:/app  # Mount your local directory to the container's directory
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Set environment variables, if needed